version: 2
jobs:
  build:
    docker:  
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: echo "Instaling node dependecies"
      - run: 'npm install'
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: echo "Running tests with Jest"
      - run: 'npm run test'

workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
