version: 2
jobs:
  build:
    docker:  
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Set up Dependencies 
          command: npm install
      - run: 
          name: Run Tests and Coverage 
          command: npm run test

workflow:
  version: 2
  build_and_test:
    jobs:
      - build
