version: 2
jobs:
  install_dependencies:
    docker:  
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Set up Dependencies 
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  run_tests:
    docker:  
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Run Tests and Coverage 
          command: npm run test
      
workflows:
  version: 2
  phase1:
    jobs:
      - install_dependencies
      - run_tests
